# Generated by Django 5.1.1 on 2024-10-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='language',
            field=models.ManyToManyField(to='language.language'),
        ),
    ]
