# Generated by Django 5.1.2 on 2024-11-09 06:36

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=250),
        ),
        migrations.AlterField(
            model_name='problems',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
