# Generated by Django 5.1.2 on 2024-11-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runcode', '0002_problems_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='status',
            field=models.CharField(choices=[('OSON', 'Osan'), ('Urta', "O'rta"), ('Qiyin', 'Qiyin')], default='OSON', max_length=10),
        ),
    ]
