# Generated by Django 5.1.2 on 2024-11-10 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runcode', '0002_alter_category_name_alter_problems_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unittestproblem',
        ),
    ]
