# Generated by Django 5.1.2 on 2024-11-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runcode', '0003_problems_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='status',
            field=models.CharField(choices=[('Oson', 'Osan'), ("O'rta", "O'rta"), ('Qiyin', 'Qiyin')], default='OSON', max_length=10),
        ),
    ]
