# Generated by Django 5.1.2 on 2024-11-11 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runcode', '0003_delete_unittestproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='function_name',
            field=models.CharField(default=datetime.datetime(2024, 11, 11, 13, 39, 48, 794114, tzinfo=datetime.timezone.utc), max_length=250),
            preserve_default=False,
        ),
    ]
