# Generated by Django 5.1.2 on 2024-11-11 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runcode', '0004_problems_function_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='function_name',
        ),
        migrations.AddField(
            model_name='problems',
            name='function_or_class_name',
            field=models.CharField(default=django.utils.timezone.now, help_text="M: def main(args1, args2, ...) yoke class class_name: kiyin funkiya nomi. class larni yozgandan so'ng tab qo'yishni unitmang!!!", max_length=250),
            preserve_default=False,
        ),
    ]
