# Generated by Django 5.1.2 on 2024-11-09 06:36

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bob',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='mavzu',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='mavzutanasi',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
