# Generated by Django 5.1.1 on 2024-10-09 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('problems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problems')),
            ],
        ),
    ]
