# Generated by Django 5.1.1 on 2024-10-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=250)),
                ('docker_image', models.CharField(max_length=250)),
                ('cmd', models.CharField(max_length=250)),
            ],
        ),
    ]
