# Generated by Django 5.1.2 on 2024-11-09 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('runcode', '0002_alter_category_name_alter_problems_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorytime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_time_code', models.TextField(help_text="misol: python dasturlash tilidagi tracemalloc (3.4 versiadan yuqorida ishlaydi) orqali yozilgan kod bo'lish kerak yoki boshqa dasturlash tilida u dasturlash tillari qo'shilgan bo'lsa")),
                ('line1', models.TextField(help_text='User uchun 1 kod(python dasturlash tilidagi tracemalloc yozilgan)')),
                ('line2', models.TextField(help_text='User uchun 1 kod(python dasturlash tilidagi tracemalloc yozilgan)')),
                ('language', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='runcode.language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runcode.problems')),
            ],
        ),
        migrations.CreateModel(
            name='Unittestproblems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_test_code', models.TextField(help_text="misol: python dasturlash tilidagi unittest orqali yozilgan kod bo'lish kerak yoki boshqa dasturlash tilida u dasturlash tillari qo'shilgan bo'lsa!!!")),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('language', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='runcode.language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runcode.problems')),
            ],
        ),
    ]
