# Generated by Django 5.1.2 on 2024-11-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unittestproblems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorytime',
            name='line1',
            field=models.TextField(help_text='User  uchun 1 kod(python dasturlash tilidagi tracemalloc yozilgan)'),
        ),
        migrations.AlterField(
            model_name='memorytime',
            name='line2',
            field=models.TextField(help_text='User  uchun 1 kod(python dasturlash tilidagi tracemalloc yozilgan)'),
        ),
    ]
