# Generated by Django 5.1.2 on 2024-11-11 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unittestproblems', '0002_alter_memorytime_line1_alter_memorytime_line2'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittestproblems',
            name='unit_test_class_name',
            field=models.CharField(default=datetime.datetime(2024, 11, 11, 20, 38, 44, 502340, tzinfo=datetime.timezone.utc), help_text="pastdagi kiritgan class nomi bo'lishi kerak!!!", max_length=100),
            preserve_default=False,
        ),
    ]
