# Generated by Django 5.1.2 on 2024-11-14 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runcode', '0005_remove_problems_function_name_and_more'),
        ('unittestproblems', '0003_unittestproblems_unit_test_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorytime',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runcode.language'),
        ),
        migrations.AlterField(
            model_name='unittestproblems',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runcode.language'),
        ),
    ]
