# Generated by Django 5.1.2 on 2024-10-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text="Ushbu foydalanuvchi tegishli bo'lgan guruhlar.", related_name='customuser_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text="Foydalanovchi ro'xsatnomalari!.", related_name='custom_user_set', to='auth.permission', verbose_name="Fofoydalanuvch ro'xsatnomalari!"),
        ),
    ]
